#!/bin/sh

cp target/x86_64-pc-windows-gnu/release/news.exe x86_64_news.exe

cp target/release/news x86_64_linux_news

cp target/aarch64-apple-darwin/release/news aarch64_news_macos

cp target/x86_64-apple-darwin/release/news x86_64_news_macos

